# Generated by Django 6.0.5 on 2026-05-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
