# Generated by Django 6.0.5 on 2026-05-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_project_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("profession", models.CharField(max_length=300)),
                ("short_bio", models.TextField()),
                ("hero_image", models.ImageField(upload_to="profile/")),
                ("resume", models.FileField(upload_to="resume/")),
                ("github", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("facebook", models.URLField(blank=True)),
                ("email", models.EmailField(max_length=254)),
                ("footer_description", models.TextField()),
                ("projects_completed", models.IntegerField(default=0)),
                ("years_experience", models.IntegerField(default=0)),
                ("technologies_used", models.IntegerField(default=0)),
            ],
        ),
    ]
