# Generated by Django 6.0.5 on 2026-05-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_milestone_skill_remove_profile_short_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="short_bio",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
