# Generated by Django 6.0.5 on 2026-05-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_profile_short_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="google_map",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(default="", max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
    ]
