# Generated by Django 6.0.5 on 2026-05-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_profile_google_map_profile_location_profile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="about_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile/"),
        ),
    ]
