# Generated by Django 6.0.5 on 2026-05-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_profile_about_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(max_length=100),
        ),
    ]
