# Generated by Django 5.2.8 on 2026-05-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_profile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("Website", "Website"),
                    ("App", "App"),
                    ("AI/ML Project", "AI/ML Project"),
                ],
                default="Website",
                max_length=50,
            ),
        ),
    ]
